name: Dev - Apply
on: [workflow_dispatch]
jobs:
  TerraformApply:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Apply
        run: |
          ls -l
          make dev-apply token=${vault_token}