name: Dev - Apply
on: [workflow_dispatch]
jobs:
  TerraformApply:
    runs-on: self-hosted
    steps:
      - name: Terraform Apply
          - uses: actions/checkout@v4
        with:
          url: http://vault.nareshdevops1218.online:8200/
          vault_token: ${{ secrets.VAULT_TOKEN }}
        run: |
          ls -l
          make dev-apply token=${vault_token}